POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvb2wiLCJpZCI6IjYwZDM1ZTlkMjAyODc4MTQyMGQ0ZjQ3MiIsImlhdCI6MTYyNDQ4NTM5MX0.kt5aRs-W0VFwRpDVwXD7ZXe7d3ylVDYNJZfch2L1huQ

{
  "title": "My blog entry",
  "author": "John Doe",
  "url": "http://blog_entry.com",
  "likes": "144"
}